version: '3.8'

services:
  # database containers, one for each db
  postgres_vmp:
    container_name: postgres_vmp
    # command:
    #   - "postgres"
    #   - "-c"
    #   - "max_connections=200"
    #   # SOLUÇÃO PARA O ERRO DE CONEXÕES IDLE ATIVAS
    #   # SELECT * FROM pg_stat_activity;
    #   # SHOW idle_in_transaction_session_timeout
    #   - "-c"
    #   - "idle_in_transaction_session_timeout=6000"
    restart: unless-stopped
    image: postgres:latest
    #ports:
    #  - "4040:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    env_file:
      - ../../.env
    networks:
      - nginx_network_vmp

  pgbouncer_vmp:
    container_name: pgbouncer_vmp
    image: edoburu/pgbouncer
    env_file:
      - ../../.env
    ports:
      - "5433:5432"
    depends_on:
      - postgres_vmp
    networks:
      - nginx_network_vmp

networks:
  nginx_network_vmp:
    name: rede_nginx_vmp

volumes:
  pgdata2:
