version: '3.8'

services:

  # web container, with django + gunicorn
  django_gunicorn_vmp:
    container_name: django_gunicorn_vmp
    restart: always
    volumes:
      - ../../.:/home/app/web
    env_file:
      - ../../.env
    build:
      context: ../../.
    networks:
      - nginx_network_vmp


  nginx_vmp:
    container_name: nginx_vmp
    restart: always
    image: nginx:latest
    ports:
      - "8889:89"
    volumes:
      - ../../static:/home/app/web/static
      - ../../media:/home/app/web/media
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network_vmp
    depends_on:
      - django_gunicorn_vmp

networks:
  nginx_network_vmp:
    name: rede_nginx_vmp

volumes:
  static:
  media:
