# Generated by Django 3.2.3 on 2022-12-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('email_compra', models.CharField(max_length=150)),
                ('num_contato', models.CharField(blank=True, max_length=15, null=True)),
                ('mac1', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
