# Generated by Django 3.2.3 on 2022-12-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20221201_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='email_compra',
            new_name='email',
        ),
    ]
